parameters:
    pomm.security.user.provider.class: Pomm\PommBundle\Security\User\PommUserProvider
    pomm.data_collector.class: Pomm\PommBundle\DataCollector\DatabaseDataCollector

services:
    pomm:
        class: Pomm\Service
    pomm.security.user.provider:
        class: "%pomm.security.user.provider.class%"
        abstract: true
        public: false
        arguments: [@pomm]
    data_collector.pomm:
        class: "%pomm.data_collector.class%"
        arguments:
            - @pomm
        tags:
            - { name: data_collector, template: "PommBundle:Collector:db.html.twig", id: "db"}
